// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0gpKpof7Dx4oDyyIIhRPJn8mkGXegiE',
    appId: '1:617154543219:web:8bf3f5bec039ce10713406',
    messagingSenderId: '617154543219',
    projectId: 'garden-1m',
    authDomain: 'garden-1m.firebaseapp.com',
    databaseURL: 'https://garden-1m-default-rtdb.firebaseio.com',
    storageBucket: 'garden-1m.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uoM2A0zvkcGmOyMNRtGGM8C99NLYjMc',
    appId: '1:617154543219:android:58d25ce47e26086b713406',
    messagingSenderId: '617154543219',
    projectId: 'garden-1m',
    storageBucket: 'garden-1m.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtSJRC17dhD9m31NW2dl8uRj_ZKEzTkQ',
    appId: '1:617154543219:ios:486c4f21255c186f713406',
    messagingSenderId: '617154543219',
    projectId: 'garden-1m',
    storageBucket: 'garden-1m.appspot.com',
    iosBundleId: 'com.example.garden1m',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtSJRC17dhD9m31NW2dl8uRj_ZKEzTkQ',
    appId: '1:617154543219:ios:ed440b15bba7cc4d713406',
    messagingSenderId: '617154543219',
    projectId: 'garden-1m',
    storageBucket: 'garden-1m.appspot.com',
    iosBundleId: 'com.example.garden1m.RunnerTests',
  );
}
